# Generated by Django 3.2.17 on 2023-02-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('refbook_id', 'date')},
        ),
    ]
