# Generated by Django 3.2.17 on 2023-02-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_version_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set(),
        ),
    ]
