# Generated by Django 3.2.17 on 2023-02-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_version_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('refbook_id', 'date'), ('refbook_id', 'version')},
        ),
    ]
